Discourse/NoChdir:
  Enabled: true
  Exclude:
    - 'spec/**/*' # Specs are run sequentially, so chdir can be used
    - 'plugins/*/spec/**/*'

Discourse/NoDirectMultisiteManipulation:
  Enabled: true

Discourse/NoTimeNewWithoutArgs:
  Enabled: true

Discourse/NoUriEscapeEncode:
  Enabled: true

Discourse/TimeEqMatcher:
  Enabled: true
