Discourse/NoChdir:
  Enabled: true
  Exclude:
    - "**/spec/**/*" # Specs are run sequentially, so chdir can be used

Discourse/NoTimeNewWithoutArgs:
  Enabled: true

Discourse/NoURIEscapeEncode:
  Enabled: true

Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: true
  Include:
    - "**/db/migrate/*"
    - "**/db/post_migrate/*"

Discourse/NoNokogiriHtmlFragment:
  Enabled: true

Discourse/NoResetColumnInformationInMigrations:
  Enabled: false
  Include:
    - "**/db/migrate/*"
    - "**/db/post_migrate/*"

# Specs

Discourse/NoDirectMultisiteManipulation:
  Enabled: true
  Include:
    - "**/spec/**/*"

Discourse/TimeEqMatcher:
  Enabled: true
  Include:
    - "**/spec/**/*"

Discourse/NoJsonParseResponse:
  Enabled: false
  Include:
    - "**/spec/**/*"

Discourse/NoMockingJobs:
  Enabled: true
  Include:
    - "**/spec/**/*"

Discourse/OnlyTopLevelMultisiteSpecs:
  Enabled: true
  Include:
    - "**/spec/**/*"

Discourse/NoMixingMultisiteAndStandardSpecs:
  Enabled: true
  Include:
    - "**/spec/**/*"

Discourse/Plugins/CallRequiresPlugin:
  Enabled: true
  Include:
    - "app/controllers/**/*"

Discourse/Plugins/UsePluginInstanceOn:
  Enabled: true

Discourse/Plugins/NamespaceMethods:
  Enabled: true
  Exclude:
    - "**/spec/**/*"
    - "**/tasks/**/*.rake"
    - "**/db/fixtures/**/*"

Discourse/Plugins/NamespaceConstants:
  Enabled: true
  Exclude:
    - "**/spec/**/*"
    - "**/tasks/**/*.rake"
    - "**/db/fixtures/**/*"

Discourse/Plugins/UseRequireRelative:
  Enabled: true

Discourse/Plugins/NoMonkeyPatching:
  Enabled: true

Discourse/Services/GroupKeywords:
  Enabled: true

Discourse/Services/EmptyLinesAroundBlocks:
  Enabled: true
