Discourse/NoChdir:
  Enabled: true
  Exclude:
    - 'spec/**/*' # Specs are run sequentially, so chdir can be used
    - 'plugins/*/spec/**/*'

Discourse/NoTimeNewWithoutArgs:
  Enabled: true

Discourse/NoURIEscapeEncode:
  Enabled: true

Discourse/NoNokogiriHtmlFragment:
  Enabled: true

# Specs

Discourse/NoDirectMultisiteManipulation:
  Enabled: true
  Patterns:
  - _spec.rb
  - "(?:^|/)spec/"

Discourse/TimeEqMatcher:
  Enabled: true
  Patterns:
  - _spec.rb
  - "(?:^|/)spec/"

Discourse/NoJsonParseResponse:
  Enabled: false
  Patterns:
  - _spec.rb
  - "(?:^|/)spec/"
